#!/bin/sh

# add a boot service to $sysroot
rc_add() {
	mkdir -p $sysroot/etc/runlevels/$2
	ln -sf /etc/init.d/$1 $sysroot/etc/runlevels/$2/$1
}

rc_add sshd default
rc_add dhcpcd default
rc_add urandom default
rc_add rngd default

chown -R root:root /root

echo "nanobox" > /etc/hostname

modprobe virtio_net

exec /sbin/init
